# 1. Numpy

### 1.1. Inner Product of Two Vectors (Arrays)

In [1]:
# import packages
import numpy as np

In [64]:
# generate random data
n = 10
r = 4

x_l = [[np.random.normal() for i in range(n)] for j in range(r)]
x_a = np.array(x_l)

y_l = [[np.random.normal() for i in range(n)] for j in range(r)]
y_a = np.array(y_l)

In [65]:
# size of the arrays
x_a.shape, y_a.shape
#x_a,y_a

((4, 10), (4, 10))

In [66]:
answer1 = np.dot(x_a, y_a.T, out=None)
answer1

array([[-0.8619657 , -9.95972265, -0.43941201,  0.83051058],
       [-3.45845666,  1.10591472,  1.25209942,  0.01093908],
       [-3.63665094, -0.9075781 ,  1.49921989,  2.08239225],
       [-0.25315099, -6.14633446,  7.64285555, -0.78177483]])

### 1.2. Mean Absolute Error of Two Vectors (Arrays)

In [67]:
answer2 = (np.sum(np.absolute(x_a-y_a)) / n)
answer2

4.9641884486084695

### 1.3. Create Lead() and Lag()

In [68]:
#def lead(ar,x):
#    return np.append(ar,np.array([np.nan for i in range(x)]))[x:]

def lead(x, n):

    y = []
    for i in range(0, len(x)):

        x_new = x[i,n:]
        NaN_Array = np.full(n, np.nan)
        a = np.concatenate((x_new, NaN_Array), axis= 0)
        y.append([a])
        
    y = np.asarray(y)

    return y

In [69]:
# example
lead(x_a,2)

array([[[-1.07248628, -1.62174196, -0.59171294,  0.87994489,
          0.46980268, -1.00660515,  1.47107188,  0.47146536,
                 nan,         nan]],

       [[ 0.38410813, -0.83387896, -0.36279545,  0.05921763,
          0.91997036,  0.40942067, -0.33446843,  1.73476989,
                 nan,         nan]],

       [[-0.81150147, -0.17127057,  0.10989537,  0.24313374,
          1.84217536,  0.65310121, -0.0070048 , -1.23897445,
                 nan,         nan]],

       [[-2.0460388 , -1.06339343,  0.99060428,  1.93388772,
         -0.96345649, -0.55740254, -1.10562207, -1.89894543,
                 nan,         nan]]])

In [70]:
#def lag(ar,x):
#    return np.append(np.array([np.nan for i in range(x)]),ar)[:ar.size-x]

def lag (x, n):

    y = []
    for i in range(0, len(x)):
        
        x_new = x[i,:-n]
        NaN_Array = np.full(n, np.nan)
        a = np.concatenate((NaN_Array, x_new), axis= 0)
        y.append([a])

    y = np.asarray(y)
    return y

In [71]:
# example
lag(x_a,2)

array([[[        nan,         nan,  1.47858241, -2.62407792,
         -1.07248628, -1.62174196, -0.59171294,  0.87994489,
          0.46980268, -1.00660515]],

       [[        nan,         nan, -0.88869013,  1.01845614,
          0.38410813, -0.83387896, -0.36279545,  0.05921763,
          0.91997036,  0.40942067]],

       [[        nan,         nan,  0.82589148,  0.78502703,
         -0.81150147, -0.17127057,  0.10989537,  0.24313374,
          1.84217536,  0.65310121]],

       [[        nan,         nan,  0.75540976,  0.40492642,
         -2.0460388 , -1.06339343,  0.99060428,  1.93388772,
         -0.96345649, -0.55740254]]])

### 1.4. Pairwise Distance

In [21]:
# generate random data
n = 10
d = 5

x_li = [[np.random.normal() for i in range(n)] for j in range(d)]
x_ar = np.array(x_li)

#y_li = [[np.random.normal() for i in range(n)]]*d
y_li = [np.random.normal() for i in range(n)]
y_ar = np.array(y_li)

In [22]:
# size of the arrays
#x_ar.shape, y_ar.shape
x_ar,y_ar

(array([[ 0.36466047,  0.93061271,  0.67847167,  0.37952763,  1.12266439,
          0.34454838,  0.99872838, -0.01220041, -0.41954548,  0.10206067],
        [-0.96649289,  0.09151914, -0.99432136,  0.43706752,  1.62747945,
         -0.28601851, -1.96189067, -0.35592528, -1.09556477, -0.60559093],
        [ 1.57028345, -1.17993621,  0.23424094, -1.42778074,  0.13524904,
          0.73089693, -0.87423538,  0.1321321 , -0.04903897,  0.5723941 ],
        [ 0.2399457 ,  0.94864879, -1.05048336, -0.55749055, -0.23698114,
         -1.01939582,  0.03188558, -0.7199038 , -0.80674783,  0.29747881],
        [-1.14844038,  0.29810522,  1.52997453, -0.27739819,  1.02149329,
          0.9305979 ,  0.26154894, -0.4511042 , -0.26155791,  2.60042301]]),
 array([ 0.07871045,  1.71139908,  0.11803138, -1.34311103, -1.0225788 ,
        -0.29304115,  1.27951758, -0.99881377, -0.33789696, -0.08341708]))

In [23]:
pairwisedist = []
y2 =  np.dot(y_ar, y_ar, out=None)
for point in range(d):
    sup = np.dot(x_ar[point], x_ar[point], out=None) + y2 - 2*np.dot(x_ar[point], y_ar, out=None)
    pairwisedist.append(sup)
answer4 = pairwisedist
answer4

[10.074877751862074,
 26.912442384217968,
 19.425515469104685,
 5.734445000299224,
 20.853220527592725]

# 2. Pandas

### 2.1. Flights

In [24]:
# import packages
import pandas as pd

In [28]:
# select file
path1 = "C:/Users/drr19/OneDrive/Bocconi - DSBA/1 - Statistics/ProbabilityAndStatistics/Assignment_1/data/nycflights13/nycflights13_weather.csv"
weather = pd.DataFrame(pd.read_csv(path1, sep=",", header=42, encoding="utf-8"))
weather["temp"] = weather["temp"].interpolate()

In [29]:
weather.head()

origin  year  month  day  hour   temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0  37.04  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1  37.04  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2  37.94  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3  37.94  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4  37.94  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00

### 2.1.1. Convert temperature to Celsius

In [54]:
# conversion -> new column
sup = (weather["temp"]-32)*5/9

temp_cpop = weather.pop('tempC')
weather.insert(6,'tempC',temp_cpop)

weather.head()

origin  year  month  day  hour   temp  tempC   dewp  humid  wind_dir  \
8708    JFK  2013      1    1     0  37.94    3.3  23.00  54.51     240.0   
8709    JFK  2013      1    1     1  37.94    3.3  24.08  57.04     250.0   
8710    JFK  2013      1    1     2  39.02    3.9  24.98  56.77     240.0   
8711    JFK  2013      1    1     3  39.02    3.9  26.06  59.37     240.0   
8712    JFK  2013      1    1     4  39.02    3.9  24.98  56.77     260.0   

      wind_speed  wind_gust  precip  pressure  visib            time_hour  \
8708    16.11092  18.540125     0.0    1014.4   10.0  2013-01-01 01:00:00   
8709    17.26170  19.864419     0.0    1013.5   10.0  2013-01-01 02:00:00   
8710    19.56326  22.513008     0.0    1013.0   10.0  2013-01-01 03:00:00   
8711    18.41248  21.188714     0.0    1013.2   10.0  2013-01-01 04:00:00   
8712    14.96014  17.215830     0.0    1013.2   10.0  2013-01-01 05:00:00   

           date  
8708 2013-01-01  
8709 2013-01-01  
8710 2013-01-01  
8711 2013-01-01  
8712 2013-01-01

### 2.1.2. Compute daily mean temperatures in JFK airport.
##### Missing data should be interpolated from the preceeding and following day.

In [55]:
# creating a date
weather["date"] = pd.to_datetime(dict(year = weather.year, month = weather.month, day = weather.day))
# filtering JFK
weather = weather[weather.origin == "JFK"]
weather.shape

(8711, 17)

In [56]:
# average per day
weather_days = weather.groupby(["date"]).mean()
weather_days.shape

(364, 14)

In [57]:
# create a lagday column
weather_days["lagday"] = np.array(list(pd.to_datetime(["2012-12-31"])) + list(weather_days.index[:weather_days.shape[0]-1]))
weather_days["dif"] = weather_days.index - weather_days["lagday"]

#check whether it needs interpolation
weather_days["dif"].max()

Timedelta('1 days 00:00:00')

### 2.1.3. Choose days with greater mean than preceeding days

In [58]:
# generates dummy array: if hotter than previous day = 1
hotter = [0]
for num in range(1,weather_days.shape[0]):
    if weather_days["temp"][num] > weather_days["temp"][num-1]:
        hotter.append(1)
    else:
        hotter.append(0)
weather_days["HotterThanYesterday"] = np.array(hotter)
weather_days.head()

year  month  day       hour       temp     tempC       dewp  \
date                                                                        
2013-01-01  2013.0    1.0  1.0  11.782609  38.871304  3.817391  24.776522   
2013-01-02  2013.0    1.0  2.0  11.500000  28.542500 -1.920833   9.837500   
2013-01-03  2013.0    1.0  3.0  11.500000  29.772500 -1.237500  13.970000   
2013-01-04  2013.0    1.0  4.0  11.500000  34.032500  1.129167  19.452500   
2013-01-05  2013.0    1.0  5.0  11.500000  36.897500  2.720833  19.197500   

                humid    wind_dir  wind_speed  wind_gust  precip     pressure  \
date                                                                            
2013-01-01  56.926087  273.478261   15.410445  17.734032     0.0  1012.663636   
2013-01-02  45.210417  320.000000   15.679378  18.043514     0.0  1017.287500   
2013-01-03  51.621667  298.333333   11.316003  13.022230     0.0  1021.225000   
2013-01-04  55.007917  256.250000   15.775276  18.153872     0.0  1017.854167   
2013-01-05  48.918750  279.166667   13.665512  15.725998     0.0  1021.262500   

            visib     lagday    dif  HotterThanYesterday  
date                                                      
2013-01-01   10.0 2012-12-31 1 days                    0  
2013-01-02   10.0 2013-01-01 1 days                    0  
2013-01-03   10.0 2013-01-02 1 days                    1  
2013-01-04   10.0 2013-01-03 1 days                    1  
2013-01-05   10.0 2013-01-04 1 days                    1

### 2.1.4. Find 5 hottest days

In [59]:
weather_days.nlargest(5, "temp")

year  month   day  hour     temp      tempC     dewp      humid  \
date                                                                            
2013-07-17  2013.0    7.0  17.0  11.5  87.0425  30.579167  66.2900  50.984167   
2013-07-16  2013.0    7.0  16.0  11.5  86.8700  30.483333  65.9675  52.828333   
2013-07-20  2013.0    7.0  20.0  11.5  86.4425  30.245833  71.9450  63.582500   
2013-07-18  2013.0    7.0  18.0  11.5  86.4350  30.241667  71.7050  63.893333   
2013-07-19  2013.0    7.0  19.0  11.5  86.3375  30.187500  75.9725  72.028750   

              wind_dir  wind_speed  wind_gust  precip     pressure      visib  \
date                                                                            
2013-07-17  222.500000    7.144426   8.221662     0.0  1020.970833  10.000000   
2013-07-16  238.333333    9.541884  10.980609     0.0  1021.312500  10.000000   
2013-07-20  236.956522   14.910106  17.158252     0.0  1008.926087   8.750000   
2013-07-18  236.086957    9.637782  11.090967     0.0  1017.020833   9.666667   
2013-07-19  192.916667   10.452918  12.029009     0.0  1013.420833   8.375000   

               lagday    dif  HotterThanYesterday  
date                                               
2013-07-17 2013-07-16 1 days                    1  
2013-07-16 2013-07-15 1 days                    1  
2013-07-20 2013-07-19 1 days                    1  
2013-07-18 2013-07-17 1 days                    0  
2013-07-19 2013-07-18 1 days                    0

## 2.2. Flights

### 2.2.1. Select all columns between Year and Day (Inclusive)

In [60]:
# select file
path2 = "C:/Users/drr19/OneDrive/Bocconi - DSBA/1 - Statistics/ProbabilityAndStatistics/Assignment_1/data/nycflights13/nycflights13_flights.csv"
flights = pd.DataFrame(pd.read_csv(path2, sep=",", header=54, encoding="utf-8"))
flights.head()

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0   
1  2013      1    1     533.0             529        4.0     850.0   
2  2013      1    1     542.0             540        2.0     923.0   
3  2013      1    1     544.0             545       -1.0    1004.0   
4  2013      1    1     554.0             600       -6.0     812.0   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0   
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0   
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0   
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0   
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0   

   distance  hour  minute            time_hour  
0      1400     5      15  2013-01-01 05:00:00  
1      1416     5      29  2013-01-01 05:00:00  
2      1089     5      40  2013-01-01 05:00:00  
3      1576     5      45  2013-01-01 05:00:00  
4       762     6       0  2013-01-01 06:00:00

In [61]:
# Define a funcion: Output as Binary List
def RangeYearDate(x,between=1):
    
    # between = 1 for columns between Year and Date
    # between = 0 for all other columns
    
    selected = []
    activate = (1-between)
    
    for keyname in list(x.keys()):
        if keyname == "year": activate = between
        if activate == between: selected.append(between)
        if activate == (1-between): selected.append((1-between))
        if keyname == "day": activate = (1-between)
            
    return selected

# Define a funcion: Output as DataFrame of selected Columns

def selectcolumns(df,lista):
    output = pd.DataFrame()
    for i in range(len(lista)):
        if lista[i] == 1:
            output[df.keys()[i]] = df[df.keys()[i]]
    return output

In [62]:
# Output as List of Binary Columns
selection_between = RangeYearDate(flights,between=1)
print(selection_between)

# Output as DataFrame
selectcolumns(flights,selection_between)

[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


year  month  day
0       2013      1    1
1       2013      1    1
2       2013      1    1
3       2013      1    1
4       2013      1    1
5       2013      1    1
6       2013      1    1
7       2013      1    1
8       2013      1    1
9       2013      1    1
10      2013      1    1
11      2013      1    1
12      2013      1    1
13      2013      1    1
14      2013      1    1
15      2013      1    1
16      2013      1    1
17      2013      1    1
18      2013      1    1
19      2013      1    1
20      2013      1    1
21      2013      1    1
22      2013      1    1
23      2013      1    1
24      2013      1    1
25      2013      1    1
26      2013      1    1
27      2013      1    1
28      2013      1    1
29      2013      1    1
...      ...    ...  ...
336746  2013      9   30
336747  2013      9   30
336748  2013      9   30
336749  2013      9   30
336750  2013      9   30
336751  2013      9   30
336752  2013      9   30
336753  2013      9   30
336754  2013      9   30
336755  2013      9   30
336756  2013      9   30
336757  2013      9   30
336758  2013      9   30
336759  2013      9   30
336760  2013      9   30
336761  2013      9   30
336762  2013      9   30
336763  2013      9   30
336764  2013      9   30
336765  2013      9   30
336766  2013      9   30
336767  2013      9   30
336768  2013      9   30
336769  2013      9   30
336770  2013      9   30
336771  2013      9   30
336772  2013      9   30
336773  2013      9   30
336774  2013      9   30
336775  2013      9   30

[336776 rows x 3 columns]

### 2.2.2. Select all other columns

In [39]:
# Output as List of Binary Columns
selection_others = RangeYearDate(flights,between=0)
print(selection_others)

# Output as DataFrame
selectcolumns(flights,selection_others)

[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


dep_time  sched_dep_time  dep_delay  arr_time  sched_arr_time  \
0          517.0             515        2.0     830.0             819   
1          533.0             529        4.0     850.0             830   
2          542.0             540        2.0     923.0             850   
3          544.0             545       -1.0    1004.0            1022   
4          554.0             600       -6.0     812.0             837   
5          554.0             558       -4.0     740.0             728   
6          555.0             600       -5.0     913.0             854   
7          557.0             600       -3.0     709.0             723   
8          557.0             600       -3.0     838.0             846   
9          558.0             600       -2.0     753.0             745   
10         558.0             600       -2.0     849.0             851   
11         558.0             600       -2.0     853.0             856   
12         558.0             600       -2.0     924.0             917   
13         558.0             600       -2.0     923.0             937   
14         559.0             600       -1.0     941.0             910   
15         559.0             559        0.0     702.0             706   
16         559.0             600       -1.0     854.0             902   
17         600.0             600        0.0     851.0             858   
18         600.0             600        0.0     837.0             825   
19         601.0             600        1.0     844.0             850   
20         602.0             610       -8.0     812.0             820   
21         602.0             605       -3.0     821.0             805   
22         606.0             610       -4.0     858.0             910   
23         606.0             610       -4.0     837.0             845   
24         607.0             607        0.0     858.0             915   
25         608.0             600        8.0     807.0             735   
26         611.0             600       11.0     945.0             931   
27         613.0             610        3.0     925.0             921   
28         615.0             615        0.0    1039.0            1100   
29         615.0             615        0.0     833.0             842   
...          ...             ...        ...       ...             ...   
336746    2123.0            2125       -2.0    2223.0            2247   
336747    2127.0            2129       -2.0    2314.0            2323   
336748    2128.0            2130       -2.0    2328.0            2359   
336749    2129.0            2059       30.0    2230.0            2232   
336750    2131.0            2140       -9.0    2225.0            2255   
336751    2140.0            2140        0.0      10.0              40   
336752    2142.0            2129       13.0    2250.0            2239   
336753    2145.0            2145        0.0     115.0             140   
336754    2147.0            2137       10.0      30.0              27   
336755    2149.0            2156       -7.0    2245.0            2308   
336756    2150.0            2159       -9.0    2250.0            2306   
336757    2159.0            1845      194.0    2344.0            2030   
336758    2203.0            2205       -2.0    2339.0            2331   
336759    2207.0            2140       27.0    2257.0            2250   
336760    2211.0            2059       72.0    2339.0            2242   
336761    2231.0            2245      -14.0    2335.0            2356   
336762    2233.0            2113       80.0     112.0              30   
336763    2235.0            2001      154.0      59.0            2249   
336764    2237.0            2245       -8.0    2345.0            2353   
336765    2240.0            2245       -5.0    2334.0            2351   
336766    2240.0            2250      -10.0    2347.0               7   
336767    2241.0            2246       -5.0    2345.0               1   
336768    2307.0            2255       12.0    2359.0            2

## 2.3. Birthdays

In [40]:
# Create sets
A = pd.read_csv("C:/Users/drr19/OneDrive/Bocconi - DSBA/1 - Statistics/ProbabilityAndStatistics/Assignment_1/data/some_birth_dates1.csv", sep=",", encoding="utf-8")
B = pd.read_csv("C:/Users/drr19/OneDrive/Bocconi - DSBA/1 - Statistics/ProbabilityAndStatistics/Assignment_1/data/some_birth_dates2.csv", sep=",", encoding="utf-8")
C = pd.read_csv("C:/Users/drr19/OneDrive/Bocconi - DSBA/1 - Statistics/ProbabilityAndStatistics/Assignment_1/data/some_birth_dates3.csv", sep=",", encoding="utf-8")
# A, B, C

### 2.3.1. A | B

In [41]:
ans1 = pd.merge(A, B, on='Name', how='outer')
ans1["BirthDate"] = ans1["BirthDate_x"]

for line in range(ans1.shape[0]):
    if str(ans1["BirthDate"][line]) == "nan":
           ans1["BirthDate"][line] = ans1["BirthDate_y"][line]

ans1 = ans1.drop(['BirthDate_x','BirthDate_y'], axis=1)
ans1

Name   BirthDate
0      Paitoon Ornwimol  26.06.1958
1          Antónia Lata  20.05.1935
2     Bertoldo Mallozzi  17.08.1972
3         Nedeljko Bukv  19.12.1921
4         Micha Kitchen  17.09.1930
5       Mefodiy Shachar  01.10.1914
6          Paul Meckler  29.09.1968
7       Katarzyna Lasko  20.10.1971
8          Åge Trelstad  07.03.1935
9   Duchanee Panomyaong  19.06.1952
10   Hushang Naigamwala  25.08.1991
11             Zhen Wei  16.11.1975
12          Jodoc Alwin  16.11.1969
13           Igor Mazał  14.05.2004
14        Noe Tae-Woong  11.07.1970

### 2.3.2. A | B | C

In [42]:
ans2 = pd.merge(ans1, C, on='Name', how='outer')
ans2["BirthDate"] = ans2["BirthDate_x"]

for line in range(ans2.shape[0]):
    if str(ans2["BirthDate"][line]) == "nan":
           ans2["BirthDate"][line] = ans2["BirthDate_y"][line]

ans2 = ans2.drop(['BirthDate_x','BirthDate_y'], axis=1)
ans2

Name   BirthDate
0      Paitoon Ornwimol  26.06.1958
1          Antónia Lata  20.05.1935
2     Bertoldo Mallozzi  17.08.1972
3         Nedeljko Bukv  19.12.1921
4         Micha Kitchen  17.09.1930
5       Mefodiy Shachar  01.10.1914
6          Paul Meckler  29.09.1968
7       Katarzyna Lasko  20.10.1971
8          Åge Trelstad  07.03.1935
9   Duchanee Panomyaong  19.06.1952
10   Hushang Naigamwala  25.08.1991
11             Zhen Wei  16.11.1975
12          Jodoc Alwin  16.11.1969
13           Igor Mazał  14.05.2004
14        Noe Tae-Woong  11.07.1970
15     Didier Cuvillier  24.04.1938
16    El Bachir al-Aziz  24.01.1999
17     Garikoitz Oguiza  27.05.1970
18       Magyar Flórián  29.12.1962
19     Eufebio Mascioli  11.06.1921
20           Aline Rush  04.09.1916
21        Lamija Osmond  11.04.1926
22       Étienne Chaney  04.09.1983
23       Ewelina Musial  01.12.1962
24             Yang Xun  13.04.1992
25  Gavrilo Dzenopoljac  21.07.1927
26             Tang Xia  28.04.1989
27         Mifune Nampo  18.10.1926
28       Mamuka Tercero  14.09.1912
29       Juba Kunimatsu  31.07.1929

### 2.3.3. A & B

In [43]:
ans3 = pd.merge(A, B, on='Name', how='inner')
ans3["BirthDate"] = ans3["BirthDate_x"]

for line in range(ans3.shape[0]):
    if str(ans3["BirthDate"][line]) == "nan":
           ans3["BirthDate"][line] = ans3["BirthDate_y"][line]

ans3 = ans3.drop(['BirthDate_x','BirthDate_y'], axis=1)
ans3

Name   BirthDate
0        Micha Kitchen  17.09.1930
1      Mefodiy Shachar  01.10.1914
2         Paul Meckler  29.09.1968
3      Katarzyna Lasko  20.10.1971
4         Åge Trelstad  07.03.1935
5  Duchanee Panomyaong  19.06.1952

### 2.3.4. A & C

In [44]:
ans4 = pd.merge(A, C, on='Name', how='inner')
ans4["BirthDate"] = ans4["BirthDate_x"]

for line in range(ans4.shape[0]):
    if str(ans4["BirthDate"][line]) == "nan":
           ans4["BirthDate"][line] = ans4["BirthDate_y"][line]

ans4 = ans4.drop(['BirthDate_x','BirthDate_y'], axis=1)
ans4

Empty DataFrame
Columns: [Name, BirthDate]
Index: []

### 2.3.5. A - B

In [45]:
ans5 = pd.DataFrame(np.setdiff1d(A.Name,B.Name))
ans5.columns = ["Name"]
ans5 = pd.merge(left=ans5,right=A, how='left', left_on='Name', right_on='Name')
ans5

Name   BirthDate
0       Antónia Lata  20.05.1935
1  Bertoldo Mallozzi  17.08.1972
2      Nedeljko Bukv  19.12.1921
3   Paitoon Ornwimol  26.06.1958